#!/bin/bash
printf "\n\n"
echo "-----A Y U D A-----"
printf "\n\n"
echo "Comando           Descripcion"
echo  "-------------------------------------------------------------------"
echo "infosis           Informacion del sistema que muestra: Memoria RAM - Arquitectura del sistema - Version del SO"
echo "---------------------------------------------------------------------"
echo "fecha             Muestra la fecha y hora actual"
echo "--------------------------------------------------------------------"
echo "buscar            Buscar un archivo en un directorio en especifico (recibe dos parametros-La carpeta y el archivo a buscar)"
echo "--------------------------------------------------------------------"
echo "creditos          Muestra los creditos de los que programaron"
echo "--------------------------------------------------------------------"
echo "Juego             Juego"
echo "------------------------------------------------------------------"
echo "musica            Escuchar musica"
echo "------------------------------------------------------------------"
echo "salir             Salir de la terminal"
printf "\n\n"
